# Generated by Django 5.2 on 2025-12-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='owner_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
